#!/bin/sh
set -euf

# treat the original working directory as the project root
LOCAL_WORKSPACE_FOLDER="${LOCAL_WORKSPACE_FOLDER:-$(pwd)}"

# run everything else
cd "$(dirname "$0")"

PROJECT_NAME="$(basename "$(readlink -f "$(pwd)/..")")"
CONTAINER_NAME="$PROJECT_NAME-devenv"
ADDITIONAL_DOCKER_ARGS=""

# override defaults with custom values
. ./config

if [ "${1-}" = '--rebuild' ]; then
  echo "$CONTAINER_NAME rebuild requested, deleting existing container..."
  docker rm "$CONTAINER_NAME" 1> /dev/null 2>&1 || :
fi

STATUS="$(docker inspect -f '{{.State.Status}}' "$CONTAINER_NAME" 2> /dev/null || :)"
if [ "$STATUS" = 'running' ]; then
  echo "$CONTAINER_NAME running, connecting to container..."
  docker exec       \
    --interactive   \
    --tty           \
    $CONTAINER_NAME \
    tmux
elif [ "$STATUS" = 'exited' ]; then
  echo "$CONTAINER_NAME stopped, restarting container..."
  docker start      \
    --interactive   \
    --attach        \
    $CONTAINER_NAME
else
  echo "$CONTAINER_NAME not found, creating container..."
  docker build .                                                \
    --build-arg USER="$USER"                                    \
    --build-arg USER_UID="$(id -u)"                             \
    --build-arg USER_GID="$(id -g)"                             \
    --build-arg DOCKER_GID="$(stat -c %g /var/run/docker.sock)" \
    --tag "$CONTAINER_NAME:latest"
  docker run                                                                 \
    --name $CONTAINER_NAME                                                   \
    --interactive                                                            \
    --tty                                                                    \
    --env "TERM=$TERM"                                                       \
    --env "LANG=$LANG"                                                       \
    --env "SHELL=/bin/bash"                                                  \
    --env "SSH_AUTH_SOCK=/ssh-agent"                                         \
    --env "LOCAL_WORKSPACE_FOLDER=$LOCAL_WORKSPACE_FOLDER"                   \
    --mount "type=bind,source=$SSH_AUTH_SOCK,target=/ssh-agent"              \
    --mount "type=bind,source=$LOCAL_WORKSPACE_FOLDER,target=/$PROJECT_NAME" \
    --mount "type=bind,source=$HOME/.gitconfig,target=$HOME/.gitconfig,ro"   \
    --mount "type=bind,source=$HOME/.tmux.conf,target=$HOME/.tmux.conf,ro"   \
    --mount "type=bind,source=$HOME/.config/kak,target=$HOME/.config/kak,ro" \
    --mount "type=bind,source=$(pwd)/.pi,target=$HOME/.pi"                   \
    --workdir "/$PROJECT_NAME"                                               \
    $ADDITIONAL_DOCKER_ARGS                                                  \
    "$CONTAINER_NAME:latest"                                                 \
    tmux
fi
